### ISSUE TITLE
20161229 股票池更新

### ISSUE THREAD

**Issue by gzMichael** [Xunlong2/stockpool#1]
股票池：

# 入选
日期 | 股票代码 | 股票名称 | 行业 | 概念板块 | 所属指数
---- | ---- | ---- | ---- | ---- | ---- | 
20161221 | 603696 | 安记食品 | 食品、饮料 | —— | ——
20161221 | 600860 | 京城股份 | 专用设备制造业 | 重组概念 , 并购重组 , 摘帽概念 | ——
20161228 | 601020 | 华钰矿业 | 采掘业 | —— | "上证380 , 上证小盘  "
20161228 | 000922 | 佳电股份 | 电气机械和器材制造业 |央企, 机器人概念, 央企重组 , 借壳上市 ,新能源汽车,风能 | ——
20161207 | 002803 | 吉宏股份 | 印刷和记录媒介复制业   | —— | 中小企业板

# 重点关注

股票代码 | 股票名称
---- | ----
300086 | 康芝药业
002735 | 王子新材
300023 | 宝德股份
601800 | 中国交建
300466 | 赛摩电气 

### 等待回落买点

股票代码 | 股票名称
---- | ---- 
000939 | 凯迪生态
002012 | 凯恩股份 

### 等待突破上下做T

股票代码 | 股票名称
---- | ---- 
 300250 | 初灵信息
601107 | 四川成渝
300175 | 朗源股份

### 中小盘

股票代码 | 股票名称
 ---- | ----
300313 | 天山生物 
601518 | 吉林高速

### 央企改革

股票代码 | 股票名称
---- | ---- 
000922 | 佳电股份 
000786 | 北新建材 
 | 000151 | 中成股份 
 | 600795 | 国电电力 
 | 002080 | 中材科技
 | 000930 | 中粮生化
 | 300105 | 龙源技术
 | 600420 | 现代制药 
 | 002066 | 瑞泰科技

### 一带一路

股票代码 | 股票名称
---- | ---- | 
 601669 | 中国电建 
 601186 | 中国铁建
 002051 | 中工国际
 600970 | 中材国际
 601117 | 中国化学 
 601618 | 中国中冶
 000151 | 中成股份
 000680 | 山推股份 
 600853 | 龙建股份 
601002 | 晋亿实业
600495 | 晋西车轴

### 有色板块

股票代码 | 股票名称 
---- | ----
000751 | 锌业股份
 000878 | 云南铜业
 000807 | 云铝股份
 603993 | 洛阳钼业 
 000060 | 中金岭南

### 观察

股票代码 | 股票名称
---- | ----
002139 | 拓邦股份    
603025 | 大豪科技
300128 | 锦富新材 
000798 | 中水渔业
300321 | 同大股份 
002645 | 华宏科技 
 002136 | 安纳达
002552 | 宝鼎科技
 002105 | 信隆健康
 002805 | 丰元股份
603159 | 上海亚虹 
000875 | 吉电股份 
600112 | 天成控股 
002040 | 南京港
300193 | 佳士科技
 300189 | 神农基因 
300028 | 金亚科技 
 002383 | 合众思壮
 600665 | 天地源
 600818 | 中路股份
 000554 | 泰山石油
 603726 | 朗迪集团
 002084 | 海鸥卫浴 
 300517 | 海波重工
 002810 | 山东赫达
002045 | 国光电器
 002287 | 奇正藏药 
 002806 | 华锋股份
 600679 | 上海凤凰 
 002271 | 东方雨虹
 002649 | 博彦科技
 002248 | 华东数控
 600623 | 华谊集团
 002045 | 国光电器
 300189 | 神农基因 
 002430 | 杭氧股份
 600623 | 华谊集团

**Comment by kanjianjiuhao** [comment]
2016.12.30 11:00 mark  84 stock

**Comment by gzMichael** [comment]
@kanjianjiuhao 你有补充的，可以在这里更新一下。

**Comment by kanjianjiuhao** [comment]
000060
000061
000151
000554
000592
000680
000751
000786
000798
000807
000875
000878
000922
000930
000939
002012
002029
002040
002045
002051
002066
002080
002084
002105
002136
002139
002248
002271
002287
002314
002383
002430
002552
002645
002649
002735
002776
002803
002805
002806
002810
300023
300028
300034
300086
300105
300128
300175
300189
300193
300250
300313
300321
300466
300517
600112
600406
600420
600495
600623
600665
600679
600737
600795
600818
600853
600860
600962
600970
601002
601020
601069
601107
601117
601186
601518
601618
601669
601800
603025
603159
603696
603726
603993

把这个存在文本里可以导入进去
@gzMichael 我被艾特了但看不到提示……

**Comment by jianyiwufeng** [comment]
# 20170103股票池：
## 寻龙一号股票组合

组合有四支股票：
600860京城股份
603696安记食品
002803吉宏股份
601020华钰矿业

其中，华钰矿业仍然处于5F二买后向上一段走势中。
京城股份是5F三买后的向上一段开启了。
安记食品是5F一买后。
吉宏股份则有望迎来5F一买。
 
## 重点关注：
（具体原因见下文中的复盘记录。）
300086康芝药业，此处疑似15F三买。后市值得期待。
603696安记食品，关注能否强力突破压力线。
002735王子新材，上升通道中。回到中轴线附近。等待5F二买。
002803吉宏股份，上升通道下沿。等5F一买确认。
300023宝德股份，60F一买。大概率确认。
601800中国交建，现在是1F一买。
 
 
## 等待回落买点：
002012凯恩股份，等待60F或15F三买。
000939凯迪生态，等60F三买。
 
## 等待突破，或上下做T：
300250初灵信息
601107四川成渝
300175朗源股份

## 重点板块和个股（谨慎买入）：
继续重点关注一带一路板块和央企改革板块，以及中小盘的游资股、庄股。但央企改革板块短线可能面临整理，需再观望一下。
 
1. 央企改革板块：
- 60F三买后向上一段。不过正回调调整以构建60F中枢。后面会有5F二卖板块，中长线继续看好，但短线面临调整。
 - 个股复盘：
>国投中鲁：等60F三买。
>龙源技术：启动初期，重点关注。
>中国船舶：等60F三买。
>中材科技：60F一买后向上一段。
>北新建材：60F三买，15F二买。
>中粮生化：等60F三买。
>佳电股份：60F要回做中枢。
 
2. 一带一路概念
- 海外工程板块。上升通道下沿附近。仍然处于60F三买后向上一段中。5F三买。
 - 概念股:
>- 中国铁建，中国电建，中国交建，中工国际，中材国际，中国化学，中国中冶，60三买后向上一段。
>- 山推股份，正回做5F二买;
>- 中成股份：5F向中枢延展。
>- 名家汇：上升通道下沿。等待5F二买确认。
>- 重点关注：中国交建、名家汇、晋亿实业
 
3. 中小盘游资股、庄股
>- 300086康芝药业
>- 603696安记食品
>- 601020华钰矿业
>- 002735王子新材
>- 002803吉宏股份
>- 601107四川成渝
>- 300023宝德股份
>- 000922佳电股份
>- 002012凯恩股份：
>- 600860京城股份
>- 300250初灵信息：股东还有点多，估计还要洗一洗。不过，当前在重要支撑位附近，较安全。可低吸。
>- 300175朗源股份：到达压力位附近。若回调到支撑线附近，可买入。若向上突破，可待回调买入。
>- 002139拓邦股份
>- 603025大豪科技：回踩年线、半年线后强势上涨。值得关注！
>- 300128锦富新材：回踩年线、半年线，然后向上。值得关注。
>- 000798中水渔业：已经收复年线、半年线。值得关注！
>- 300321同大股份：没能形成60F三买。但站稳年线。继续观察。
>- 601518吉林高速：15F二卖。观望。
>- 凯迪生态：期待60F三买。
>- 300313天山生物，仍然处于沿半年线的上升通道中。
>- 002645华宏科技：上升通道中。但60F三买没有了。要再观望。
>- 002136安纳达：年线、半年线上方，向上放量突破收敛区间，然后高位整理几天，都是吸筹嫌疑。
>- 002552宝鼎科技：到了压力线附近，关注之。
>- 300466赛摩电气：可关注。
>- 002767先锋电子：中轴线附近震荡，获得支撑，值得关注。
>- 信隆健康：等60F三买。
 

## 当日异动：
 - 002545东方铁塔：上升通道中。等5F三买。
- 002300太阳电缆：等30F二买。
- 300331苏大维格
- 600889南京化纤：值得关注。
- 603688石英股份：值得关注。
- 002430杭氧股份

**Comment by kanjianjiuhao** [comment]
2017.01.03 14:28 mark 91 stock

**Comment by jianyiwufeng** [comment]
# 20170104 股票池[重点关注中选股，其他谨慎]
## 寻龙一号股票组合
今日盘中将王子新材（13:39， 49.50元）和康芝药业（14:45， 14.64元）组合。至此，组合有五支股票：
**600860京城股份**
**603696安记食品**
**002803吉宏股份**
**300086康芝药业**
**002735王子新材**
 
**华钰矿业仍是重点关注对象。**
 其中，华钰矿业仍然处于5F二买后向上一段走势中，有线段背驰的嫌疑。若是回落，可以等二买再回补。
京城股份是5F三买后的向上一段。
安记食品是5F一买后。
吉宏股份迎来5F一买。
康芝药业：今天是15F三买后的向上一段。尾盘有个疑似1F三买的机会。此股离主升浪越来越近了。
 王子新材：回调到中轴线附近。5F，疑似5F二买。
 
## 重点关注：
 
>> 华钰矿业
> 中国交建
> 石英股份
> 杭氧股份
> 中水渔业
> 龙源技术
> 北新建材
> 名家汇
> 龙建股份
> 赛摩电气
> 电光科技

其中北新建材、石英股份等在短线买点附近。
 
300023宝德股份，60F一买。大概率确认。
601800中国交建，仍然是60F三买后向上一段。短线需等待方向选择。
 
000922佳电股份,5F三买后的向上一段。机会已经错过，只能等以后了。
 
603688石英股份：上沿通道中。等待确认5F三买。
 
002430杭氧股份：突破了年线半年线和夺力线。值得**重点关注**。可以等60F二买。或5F三买。
 
000798中水渔业,回踩年线、半年线后强势弹起。值得重点关注。等5F三买。
 
与杭氧股份、中水渔业类似地，值得关注的还有海鸥卫浴。
 
002730电光科技,回踩年线、半年线；60F三买确认；等5F三买入场。
 
等待回落买点：
> 002012凯恩股份，等待60F或15F三买。
> 000939凯迪生态，等60F三买。
 
等待突破，或上下做T：
> 300250初灵信息
> 601107四川成渝
> 300175朗源股份
 
## 重点板块和个股：
继续重点关注一带一路板块和央企改革板块，以及中小盘的游资股、庄股。今日佳电股份引领央企改革板块上涨，减小了短线调整的可能性。
 
1. 央企改革板块

60F三买后向上一段。不过正回调调整以构建60F中枢。后面会有5F二卖。板块中长线继续看好，但短线面临调整。
 
央企改革板块个股复盘
 
> 国投中鲁：等60F三买。
> 龙源技术：启动初期，重点关注。
> 中国船舶：等60F三买。
> 中材科技：60F一买后向上一段。等60F二买。
> 北新建材：60F三买，15F二买。
> 中粮生化：等60F三买。
> 佳电股份：耐心等待后面的机会。
 
重点关注：国投中鲁、龙源技术、北新建材、佳电股份
 
2. 一带一路概念
海外工程板块上升通道下沿附近。仍然处于60F三买后向上一段中。5F三买。
 
> 一带一路概念股:
> 中国铁建，中国电建，中国交建，中工国际，中材国际，中国化学，中国中冶,60三买后向上一段。
> 山推股份，正回做5F二买。
> 中成股份：5F向中枢延展。
> 龙建股份：疑似5F三买。
>  名家汇：上升通道下沿。等待5F二买确认。
 
**重点关注：中国交建、名家汇、龙建股份**
 
## 中小盘游资股、庄股
300086康芝药业：
 603696安记食品
 601020华钰矿业
 002735王子新材
 002803吉宏股份
 601107四川成渝
 300023宝德股份
 000922佳电股份
 002012凯恩股份：
 600860京城股份
 300250初灵信息：股东还有点多，估计还要洗一洗。不过，当前在重要支撑位附近，较安全。可低吸。
 300175朗源股份：到达压力位附近。若回调到支撑线附近，可买入。若向上突破，可待回调买入。
 002139拓邦股份
 603025大豪科技：回踩年线、半年线后强势上涨。值得关注！
 300128锦富新材：回踩年线、半年线，然后向上。值得关注。
 000798中水渔业：已经收复年线、半年线。值得关注！
 300321同大股份：没能形成60F三买。但站稳年线。继续观察。
 601518吉林高速15F二卖。观望。
 凯迪生态:期待60F三买。
 300313天山生物:仍然处于沿半年线的上升通道中。
 002645华宏科技:上升通道中。但60F三买没有了。要再观望。
 002136安纳达:年线、半年线上方，向上放量突破收敛区间，然后高位整理几天，都是吸筹嫌疑。
 002552宝鼎科技:到了压力线附近，关注之。
 300466赛摩电气:疑似15F一买后的走势。可关注。
 002767先锋电子:中轴线附近震荡，获得支撑，值得关注。
 信隆健康:等60F三买。
 002545东方铁塔:上升通道中。等5F三买。
 002300太阳电缆:等30F二买。
 300331苏大维格
 600889南京化纤:值得关注。
 

## 当日异动：
002730电光科技:回踩年线、半年线；60F三买确认；等5F三买入场。
 002661克明面业:放量突破年线、半年线。等5F三买。
 000628高新发展:回踩年线、半年线。等5F三买。
 300143星河生物:上升通道下沿，年线半年线附近。等5F二买。
 002800天顺股份:60F一买嫌疑。
 601628中国人寿:60F三买向上一段。
 300416苏试试验:等5F三买。

**Comment by jianyiwufeng** [comment]
# 20170105 股票池
## 寻龙一号股票组合
今日盘中将名家汇放入组合（13:49，价格49.26）至此，组合有六支股票：

**600860京城股份**
**603696安记食品**
**002803吉宏股份**
**300086康芝药业**
**002735王子新材**
**300506名家汇**
 
华钰矿业仍是重点关注对象。其中，华钰矿业仍然处于5F二买后向上一段走势中，有线段背驰的嫌疑。若是回落，可以等二买再回补。

京城股份是构造5F中枢后向上离开中枢的过程中。仍然是向上的趋势行情中。
安记食品是5F一买后，目前看来仍有点弱，再观察观察。

吉宏股份是回落做5F二买，继续看多。
 
康芝药业：仍然看好，主拉升还没到。不过短线需关注15F向上一段何时结束。
 
王子新材：回调到中轴线附近。5F二买后的向上一段中。

 
## 重点关注：
>  中水渔业
> 电光科技
> 名家汇
> 石英股份
> 华钰矿业
> 中国交建
> 杭氧股份
> 龙源技术
> 北新建材
> 赛摩电气
 
等短线买点：
> 300416苏试试验
> 300143星河生物
> 000628高新发展
> 002661克明面业
> 002545东方铁塔
 
等待回落中线买点：
> 002012凯恩股份，等待60F或15F三买。
> 000939凯迪生态，等60F三买。
>  300023宝德股份，60F一买。大概率确认。
> 601800中国交建，仍然是60F三买后向上一段。短线需等待方向选择。
>  000922佳电股份:5F三买后的向上一段。机会已经错过，只能等以后了。
>  603688石英股份：上升通道中。疑似5F三买。
>  002430杭氧股份：突破了年线半年线和夺力线。值得重点关注。可以等60F二买。或5F三买。
>  000798中水渔业回踩年线、半年线后强势弹起。值得重点关注。等5F三买。
>  与杭氧股份、中水渔业类似地，值得关注的还有海鸥卫浴。
>  002730电光科技,回踩年线、半年线；60F三买确认；等5F三买入场。
>  300250初灵信息已经逐步向上突破平台，应该更加关注它了。
 
等待突破，或上下做T：
> 601107四川成渝
> 300175朗源股份
 
## 重点板块和个股：
继续重点关注一带一路板块和央企改革板块，以及中小盘的游资股、庄股。今日佳电股份引领央企改革板块上涨，减小了短线调整的可能性,但仍不能排除。。
 
1. 央企改革板块

60F三买后向上一段。不过正回调调整以构建60F中枢。后面会有5F二卖。板块中长线继续看好，但短线面临调整。
 
央企改革板块个股复盘
 
> 国投中鲁：等60F三买。
> 龙源技术：启动初期，重点关注。
> 中国船舶：等60F三买。
> 中材科技：60F一买后向上一段。等60F二买。
> **北新建材：60F三买，15F二买。**
> 中粮生化：等60F三买。
> 佳电股份：耐心等待后面的机会。
 
重点关注：国投中鲁、龙源技术、北新建材、佳电股份
 
2. 一带一路概念
海外工程板块上升通道下沿附近。仍然处于60F三买后向上一段中。5F三买。
 
> 一带一路概念股:
> 中国铁建，中国电建，中国交建，中工国际，中材国际，中国化学，中国中冶,60三买后向上一段。
> 山推股份，正回做5F二买。
> 中成股份：今日低点是一分钟三买。不过级别太小
> 龙建股份：疑似5F三买。
>  名家汇：上升通道下沿。**5F二买确认。**
 
**重点关注：中国交建、名家汇、龙建股份**
 
## 中小盘游资股、庄股
**300086康芝药业：**
 603696安记食品
 601020华钰矿业
 002735王子新材
 002803吉宏股份
 601107四川成渝
 300023宝德股份
 000922佳电股份
 002012凯恩股份：
 600860京城股份
300175朗源股份：到达压力位附近。若回调到支撑线附近，可买入。若向上突破，可待回调买入。
 凯迪生态:期待60F三买。 
**300313天山生物,仍然处于沿半年线的上升通道中,等5F、15F三买。**
 002136安纳达: 年线、半年线上方，向上放量突破收敛区间，然后高位整理几天，都是吸筹嫌疑。现有向上突破的倾向
 300466赛摩电气:疑似15F一买后的走势。可关注。
002661克明面业，放量突破年线、半年线。等5F三买。
 000628高新发展，回踩年线、半年线。等5F三买。
 300143星河生物，上升通道下沿，年线半年线附近。等5F二买。
 002800天顺股份，60F一买嫌疑。
 300416苏试试验，等5F三买。

  

## 当日异动：
> 300340 科恒股份，值得关注。
>  000755 山西三维，等5F三买。
>  600071 凤凰光学，值得关注。
>  002759 天际股份，60F一买。
>  300505 川金诺，触碰半年线和上升通道下沿后有望反弹。
>  002140 东华科技：60F一买后。值得关注。
>  002637赞宇科技：上升通道中。

## 其他关注：

> 002139拓邦股份，等5F三买。
> 603025大豪科技：回踩年线、半年线后强势上涨。值得关注！
> 300128锦富新材：回踩年线、半年线，然后向上。值得关注。
> 002552宝鼎科技：到了压力线附近，关注之。
> 300321同大股份：没能形成60F三买。但站稳年线。继续观察。
> **601518吉林高速：15F二卖。观望。**
> 002645华宏科技：上升通道下沿附近。但60F三买没有了。要再观望。
> 002767先锋电子中轴线附近震荡，获得支撑，值得关注。
> 信隆健康：等60F三买。
> 002545东方铁塔：上升通道中。等5F三买。
> 002300太阳电缆：等30F二买。
> 300331苏大维格
> 600889南京化纤：值得关注。
> 601628中国人寿：60F三买向上一段。

**Comment by gzMichael** [comment]
2016年12月已结束，close。
